### ISSUE TITLE
aim after x bullets/ stop after x bullets

### ISSUE THREAD

**Issue by GioFrandiz** [deboogerxyz/ah4#6]
plz my friend if it possible to add this featur to enable aimbot on x shots

**Comment by deboogerxyz** [comment]
Sure! I will add it today.

**Comment by deboogerxyz** [comment]
Added!

**Comment by GioFrandiz** [comment]
OMG! u´re da boss, really ty!
gonna test this amazing feature, i think its a cool "legit" option so it doesn't seem so obvious and activate the aimbot after x shots :)

**Comment by deboogerxyz** [comment]
To be completely honest, I think it's useless, at least for me. But it's really easy to add. Enjoy. ^^
